sonar.projectKey=devops-project
sonar.projectName=devops-project

sonar.sources=.
sonar.language=py

sonar.sourceEncoding=UTF-8

# EXCLUSION CRITIQUE (ça règle 80% de ton problème)
sonar.exclusions=\
venv/**,\
**/__pycache__/**,\
**/*.pyc,\
node_modules/**,\
**/*.js,\
**/*.ts,\
**/*.html,\
**/*.css,\
ansible/**,\
*.log

# IMPORTANT pour éviter les bugs JS WebSocket
sonar.javascript.enabled=false
sonar.typescript.enabled=false
