- name: Deploy Flask App with Docker
  hosts: localhost
  become: yes

  tasks:

    - name: Stop ancien container
      shell: docker rm -f flask-app || true

    - name: Build image Docker
      shell: docker build -t flask-app ..

    - name: Run container
      shell: docker run -d -p 5000:5000 --name flask-app flask-app
